        <produto>
              <id_produto>{product_id}</id_produto>
              <codigo_de_barras>{product_cod}</codigo_de_barras>
              <link_produto>{product_url}</link_produto>
              <titulo>{product_title}</titulo>
              <preco>{product_price}</preco>
              <parcelamento>{product_portions}</parcelamento>
              <imagem>{product_image}</imagem>
              <categoria>{product_category}</categoria>
        </produto>